package edu.cmu.tetrad.sem;

import edu.cmu.tetrad.data.DataSet;
import edu.cmu.tetrad.data.DataTransforms;
import edu.cmu.tetrad.data.DataUtils;
import edu.cmu.tetrad.graph.Node;

import java.util.ArrayList;
import java.util.List;

/**
 * The {@code TrainedDagAdequacy} class provides methods to evaluate the adequacy of a trained
 * Directed Acyclic Graph (DAG) by comparing real data and simulated data generated from
 * the DAG model. It computes node-level and global metrics to assess the quality of the simulation.
 *
 * <p>This class includes several metrics to evaluate the comparison:
 * - Node-level improvement in prediction (mean improvement and fraction of improved nodes).
 * - Maximum Mean Discrepancy (MMD) between real and simulated data.
 *
 * The evaluation process involves standardizing the datasets, estimating baseline metrics
 * from real data, simulating data from the DAG model, and comparing the results.
 */
public final class TrainedDagAdequacy {

    /**
     * Private constructor to prevent instantiation of this utility class.
     */
    private TrainedDagAdequacy() {}

    /**
     * Evaluates the adequacy of a trained DAG simulator by comparing simulated data with real data.
     * The method calculates improvements over a baseline for each node, computes a Mean Maximum
     * Discrepancy (MMD^2) metric to measure global similarity between real and simulated data,
     * and generates a report summarizing node and overall adequacy.
     *
     * @param real The real dataset to be used as a reference for adequacy evaluation.
     * @param simulated The dataset generated by the simulator to be evaluated.
     * @param simulator The trained DAG simulator containing node-level reports and corresponding statistics.
     * @param params Parameters governing the evaluation, including settings for MMD calculation.
     * @return An {@code AdequacyReport} containing metrics such as mean improvement, fraction of nodes improved,
     *         MMD^2 value, and per-node adequacy summaries.
     */
    public static AdequacyReport evaluate(
            DataSet real,
            DataSet simulated,
            TrainedDagSimulatorGNM simulator,
            AdequacyParams params) {

        real = DataTransforms.standardizeData(real);
        simulated = DataTransforms.standardizeData(simulated);

        List<NodeAdequacySummary> summaries = new ArrayList<>();

        double totalImprovement = 0.0;
        int improved = 0;
        int count = 0;

        for (TrainedDagSimulatorGNM.NodeReport r : simulator.getNodeReports()) {

            boolean isRoot = (r.parents == null || r.parents.isEmpty());

            double holdout = r.discreteChild ? r.xentTrain : r.mseTrain;
            double baseline = estimateBaseline(real, r);

            double improvement;

            if (isRoot) {
                improvement = 0.0;
                if (!Double.isFinite(holdout) && Double.isFinite(baseline)) holdout = baseline;
                if (!Double.isFinite(baseline) && Double.isFinite(holdout)) baseline = holdout;
            } else if (Double.isFinite(holdout) && Double.isFinite(baseline)) {
                improvement = baseline - holdout;
            } else {
                improvement = Double.NaN;
            }

            NodeAdequacySummary s = new NodeAdequacySummary(
                    r.node, r.discreteChild, r.parents, holdout, baseline);

            summaries.add(s);

            if (Double.isFinite(improvement)) {
                totalImprovement += improvement;
                count++;
                if (improvement > 0) improved++;
            }
        }

        double meanImprovement = (count > 0) ? totalImprovement / count : Double.NaN;
        double fracImproved = (count > 0) ? improved / (double) count : Double.NaN;

        double[][] X = toNumericMatrix(real);
        double[][] Y = toNumericMatrix(simulated);

        double sigma = 1.0;

        double mmd2 = RandomFeatureMMD.compute(
                X, Y,
                params.mmdFeatures,
                params.mmdSeed,
                sigma,
                params.mmdMaxRows);

//        double sigma = 1.0;  // assume roughly standardized data
//
//        double mmd2 = ExactRbfMMD.compute(
//                X,
//                Y,
//                sigma,
//                params.mmdMaxRows   // optional truncation
//        );

        return new AdequacyReport(
                meanImprovement,
                fracImproved,
                mmd2,
                summaries);
    }

    private static double estimateBaseline(DataSet data,
                                           TrainedDagSimulatorGNM.NodeReport r) {

        int col = data.getColumn(data.getVariable(r.node));

        if (!r.discreteChild) {
            double mean = 0.0;
            int n = 0;
            for (int i = 0; i < data.getNumRows(); i++) {
                double v = data.getDouble(i, col);
                if (!Double.isFinite(v)) continue;
                mean += v;
                n++;
            }
            mean /= Math.max(1, n);

            double mse = 0.0;
            for (int i = 0; i < data.getNumRows(); i++) {
                double v = data.getDouble(i, col);
                if (!Double.isFinite(v)) continue;
                double e = v - mean;
                mse += e * e;
            }
            return mse / Math.max(1, n);

        } else {
            // crude baseline: entropy of empirical distribution
            int L = r.numLevels;
            double[] counts = new double[L];
            int n = 0;
            for (int i = 0; i < data.getNumRows(); i++) {
                int v = TrainedDagSimulatorGNM.safeGetInt(data, i, col);
                if (v < 0 || v >= L) continue;
                counts[v]++;
                n++;
            }

            double xent = 0.0;
            for (int k = 0; k < L; k++) {
                if (counts[k] == 0) continue;
                double p = counts[k] / n;
                xent -= p * Math.log(p);
            }
            return xent;
        }
    }

    private static double[][] toNumericMatrix(DataSet d) {
        int n = d.getNumRows();
        int p = d.getNumColumns();
        double[][] out = new double[n][p];

        for (int i = 0; i < n; i++) {
            for (int j = 0; j < p; j++) {
                if (d.getVariable(j) instanceof edu.cmu.tetrad.data.DiscreteVariable) {
                    out[i][j] = TrainedDagSimulatorGNM.safeGetInt(d, i, j);
                } else {
                    out[i][j] = d.getDouble(i, j);
                }
            }
        }
        return out;
    }
}