package edu.cmu.tetrad.test;

import edu.cmu.tetrad.data.BoxDataSet;
import edu.cmu.tetrad.data.ContinuousVariable;
import edu.cmu.tetrad.data.DataSet;
import edu.cmu.tetrad.data.DiscreteVariable;
import edu.cmu.tetrad.data.MixedDataBox;
import edu.cmu.tetrad.graph.Edge;
import edu.cmu.tetrad.graph.Edges;
import edu.cmu.tetrad.graph.Graph;
import edu.cmu.tetrad.graph.GraphTransforms;
import edu.cmu.tetrad.graph.Node;
import edu.cmu.tetrad.graph.RandomGraph;
import edu.cmu.tetrad.search.Boss;
import edu.cmu.tetrad.search.Pc;
import edu.cmu.tetrad.search.PermutationSearch;
import edu.cmu.tetrad.search.score.BasisFunctionBicScore;
import edu.cmu.tetrad.search.score.FfMl;
import edu.cmu.tetrad.search.test.FfCi;
import edu.cmu.tetrad.search.test.FfCiContinuous;
import edu.cmu.tetrad.search.test.IndTestBasisFunctionLrt;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Random;
import java.util.Set;

/**
 * <p><b>BfVsFfHarness: Basis Function (BF-BIC / BF-LRT) vs. Feature-Function (FFML / FF-CI)
 * accuracy comparison on simulated mixed data.</b></p>
 *
 * <p>Hand-run harness (main-style, not a JUnit test). Simulates mixed continuous/discrete data
 * from random DAGs under two ground-truth regimes and compares structure-recovery accuracy of
 * BOSS under the BF-BIC score against BOSS under the FFML score (and, optionally, PC under
 * BF-LRT against PC under FF-CI).</p>
 *
 * <p><b>Regimes:</b></p>
 * <ul>
 *   <li><b>POLY</b> — conditional means are low-order polynomials: linear + quadratic main
 *       effects for continuous parents, additive level offsets for discrete parents. This is
 *       (approximately) inside the BF hypothesis space.</li>
 *   <li><b>GP</b> — conditional means are draws from an approximate Gaussian process via
 *       Random Fourier Features, with a <em>separate function draw per joint discrete-parent
 *       level</em> (fully interactionful). This is squarely in FF territory and outside any
 *       fixed low-order basis.</li>
 * </ul>
 *
 * <p>In both regimes, discrete children are generated by multinomial logit with per-level
 * utilities built from the same function class as the regime. The systematic component of every
 * child is standardized to unit variance before noise is added, so signal-to-noise is controlled
 * by {@code noiseSd} uniformly across regimes and parent-set sizes.</p>
 *
 * <p><b>Metrics</b> (estimated CPDAG vs. CPDAG of the true DAG): adjacency precision/recall/F1
 * and arrowhead precision/recall (directed endpoints in the estimated CPDAG judged against
 * directed endpoints in the true CPDAG).</p>
 *
 * <p><b>Usage</b> (defaults shown; all args are {@code key=value}):</p>
 *
 * <pre>
 * java -cp tetrad-current.jar:harness-out edu.cmu.tetrad.test.BfVsFfHarness \
 *     nodes=15 avgDeg=3 pDisc=0.3 levels=3 \
 *     ns=200,1000 seeds=5 regimes=POLY,GP noiseSd=0.5 \
 *     trunc=3 penaltyDiscount=2 singLambda=0.0 \
 *     catRhos=0.0,0.5 numFeatures=50 ffLambda=1.0 \
 *     tests=false alpha=0.01 numFeatXY=10 numFeatZ=100 approx=GAMMA \
 *     out=bf_vs_ff_results.csv
 * </pre>
 *
 * <p>Notes:</p>
 * <ul>
 *   <li>{@code seeds=k} runs seeds {@code 0..k-1}; each seed fixes the DAG, the generating
 *       functions, the noise, and the FF feature draws ({@code FfMl.setBaseSeed}).</li>
 *   <li>Each (regime, n, seed) cell runs one BF arm and one FFML arm per {@code catRhos} entry,
 *       all on the identical dataset.</li>
 *   <li>{@code tests=true} adds PC+BF-LRT and PC+FF-CI arms (FF-CI run once per catRho).</li>
 *   <li>Failures in any single arm are caught and recorded as an ERROR row; the sweep continues.</li>
 *   <li>Output CSV columns:
 *       {@code regime,n,seed,algo,params,trueEdges,estEdges,adjP,adjR,adjF1,ahP,ahR,elapsedMs,status}.</li>
 * </ul>
 */
public final class BfVsFfHarness {

    private BfVsFfHarness() {
    }

    // ============================== main ==============================

    /**
     * Entry point. See class Javadoc for arguments.
     *
     * @param args key=value arguments.
     * @throws Exception if the output file cannot be written.
     */
    public static void main(String[] args) throws Exception {
        Map<String, String> a = parseArgs(args);

        int nodes = intArg(a, "nodes", 15);
        double avgDeg = dblArg(a, "avgDeg", 3.0);
        double pDisc = dblArg(a, "pDisc", 0.3);
        int levels = intArg(a, "levels", 3);
        int[] ns = intListArg(a, "ns", new int[]{200, 1000});
        int seeds = intArg(a, "seeds", 5);
        String[] regimes = strListArg(a, "regimes", new String[]{"POLY", "GP"});
        double noiseSd = dblArg(a, "noiseSd", 0.5);

        int trunc = intArg(a, "trunc", 3);
        double penaltyDiscount = dblArg(a, "penaltyDiscount", 2.0);
        double singLambda = dblArg(a, "singLambda", 0.0);

        double[] catRhos = dblListArg(a, "catRhos", new double[]{0.0, 0.5});
        int numFeatures = intArg(a, "numFeatures", 50);
        double ffLambda = dblArg(a, "ffLambda", 1.0);

        boolean tests = boolArg(a, "tests", false);
        double alpha = dblArg(a, "alpha", 0.01);
        int numFeatXY = intArg(a, "numFeatXY", 10);
        int numFeatZ = intArg(a, "numFeatZ", 100);
        String approx = a.getOrDefault("approx", "GAMMA");

        String out = a.getOrDefault("out", "bf_vs_ff_results.csv");

        int numEdges = (int) Math.round(nodes * avgDeg / 2.0);

        System.out.println("# BfVsFfHarness  nodes=" + nodes + " edges=" + numEdges
                + " pDisc=" + pDisc + " levels=" + levels + " noiseSd=" + noiseSd);
        System.out.println("# ns=" + Arrays.toString(ns) + " seeds=" + seeds
                + " regimes=" + Arrays.toString(regimes));
        System.out.println("# BF: trunc=" + trunc + " penaltyDiscount=" + penaltyDiscount
                + " singLambda=" + singLambda);
        System.out.println("# FF: catRhos=" + Arrays.toString(catRhos)
                + " numFeatures=" + numFeatures + " ffLambda=" + ffLambda);
        if (tests) {
            System.out.println("# tests=true alpha=" + alpha + " numFeatXY=" + numFeatXY
                    + " numFeatZ=" + numFeatZ + " approx=" + approx);
        }

        String header = "regime,n,seed,algo,params,trueEdges,estEdges,adjP,adjR,adjF1,ahP,ahR,elapsedMs,status";
        List<String> rows = new ArrayList<>();
        System.out.println(header);

        for (String regime : regimes) {
            for (int n : ns) {
                for (int seed = 0; seed < seeds; seed++) {
                    Sim sim = simulate(regime, nodes, numEdges, pDisc, levels, n, noiseSd, seed);
                    Graph trueCpdag = GraphTransforms.dagToCpdag(sim.dag);
                    int trueEdges = trueCpdag.getNumEdges();

                    // ---- BOSS + BF-BIC ----
                    {
                        String params = "trunc=" + trunc + ";pd=" + penaltyDiscount;
                        Result r = runArm(() -> {
                            BasisFunctionBicScore score =
                                    new BasisFunctionBicScore(sim.data, trunc, singLambda);
                            score.setPenaltyDiscount(penaltyDiscount);
                            Boss boss = new Boss(score);
                            boss.setNumStarts(1);
                            return new PermutationSearch(boss).search();
                        }, trueCpdag);
                        emit(rows, regime, n, seed, "BOSS-BF", params, trueEdges, trueCpdag, r);
                    }

                    // ---- BOSS + FFML, per catRho ----
                    for (double rho : catRhos) {
                        String params = "rho=" + rho + ";m=" + numFeatures + ";lam=" + ffLambda;
                        final int fSeed = seed;
                        Result r = runArm(() -> {
                            FfMl score = new FfMl(sim.data);
                            score.setNumFeatures(numFeatures);
                            score.setLambda(ffLambda);
                            score.setCatRho(rho);
                            score.setBaseSeed(1000L * fSeed + 17L);
                            Boss boss = new Boss(score);
                            boss.setNumStarts(1);
                            return new PermutationSearch(boss).search();
                        }, trueCpdag);
                        emit(rows, regime, n, seed, "BOSS-FFML", params, trueEdges, trueCpdag, r);
                    }

                    if (tests) {
                        // ---- PC + BF-LRT ----
                        {
                            String params = "trunc=" + trunc + ";alpha=" + alpha;
                            Result r = runArm(() -> {
                                IndTestBasisFunctionLrt test =
                                        new IndTestBasisFunctionLrt(sim.data, trunc, singLambda);
                                test.setAlpha(alpha);
                                return new Pc(test).search();
                            }, trueCpdag);
                            emit(rows, regime, n, seed, "PC-BFLRT", params, trueEdges, trueCpdag, r);
                        }

                        // ---- PC + FF-CI, per catRho ----
                        for (double rho : catRhos) {
                            String params = "rho=" + rho + ";alpha=" + alpha
                                    + ";mXY=" + numFeatXY + ";mZ=" + numFeatZ + ";approx=" + approx;
                            Result r = runArm(() -> {
                                FfCi test = new FfCi(sim.data);
                                test.setAlpha(alpha);
                                test.setCatRho(rho);
                                test.setNumFeaturesXY(numFeatXY);
                                test.setNumFeaturesZ(numFeatZ);
                                test.setApproximation(
                                        FfCiContinuous.Approx.valueOf(approx));
                                return new Pc(test).search();
                            }, trueCpdag);
                            emit(rows, regime, n, seed, "PC-FFCI", params, trueEdges, trueCpdag, r);
                        }
                    }
                }
            }
        }

        try (PrintWriter pw = new PrintWriter(out)) {
            pw.println(header);
            for (String row : rows) pw.println(row);
        }
        System.out.println("# Wrote " + rows.size() + " rows to " + out);

        printSummary(rows);
    }

    // ============================== arms & metrics ==============================

    private interface Arm {
        Graph search() throws Exception;
    }

    private record Result(Graph est, long elapsedMs, String status) {
    }

    private static Result runArm(Arm arm, Graph trueCpdag) {
        long t0 = System.currentTimeMillis();
        try {
            Graph est = arm.search();
            return new Result(est, System.currentTimeMillis() - t0, "OK");
        } catch (Throwable t) {
            String msg = t.getClass().getSimpleName() + ":"
                    + String.valueOf(t.getMessage()).replaceAll("[,\n]", ";");
            return new Result(null, System.currentTimeMillis() - t0, "ERROR " + msg);
        }
    }

    private static void emit(List<String> rows, String regime, int n, int seed,
                             String algo, String params, int trueEdges,
                             Graph trueCpdag, Result r) {
        String row;
        if (r.est == null) {
            row = String.join(",", regime, String.valueOf(n), String.valueOf(seed), algo, params,
                    String.valueOf(trueEdges), "NA", "NA", "NA", "NA", "NA", "NA",
                    String.valueOf(r.elapsedMs), r.status);
        } else {
            double[] m = metrics(trueCpdag, r.est);
            row = String.join(",", regime, String.valueOf(n), String.valueOf(seed), algo, params,
                    String.valueOf(trueEdges), String.valueOf(r.est.getNumEdges()),
                    fmt(m[0]), fmt(m[1]), fmt(m[2]), fmt(m[3]), fmt(m[4]),
                    String.valueOf(r.elapsedMs), r.status);
        }
        rows.add(row);
        System.out.println(row);
    }

    private static String fmt(double v) {
        return Double.isNaN(v) ? "NA" : String.format(Locale.US, "%.4f", v);
    }

    /**
     * Returns {adjP, adjR, adjF1, ahP, ahR} of est vs. trueCpdag, matched by node name.
     */
    private static double[] metrics(Graph trueCpdag, Graph est) {
        Set<String> trueAdj = adjacencyKeys(trueCpdag);
        Set<String> estAdj = adjacencyKeys(est);

        int adjTp = 0;
        for (String k : estAdj) if (trueAdj.contains(k)) adjTp++;
        double adjP = estAdj.isEmpty() ? Double.NaN : adjTp / (double) estAdj.size();
        double adjR = trueAdj.isEmpty() ? Double.NaN : adjTp / (double) trueAdj.size();
        double adjF1 = (Double.isNaN(adjP) || Double.isNaN(adjR) || adjP + adjR == 0)
                ? Double.NaN : 2 * adjP * adjR / (adjP + adjR);

        Set<String> trueArr = arrowKeys(trueCpdag);
        Set<String> estArr = arrowKeys(est);
        int arrTp = 0;
        for (String k : estArr) if (trueArr.contains(k)) arrTp++;
        double ahP = estArr.isEmpty() ? Double.NaN : arrTp / (double) estArr.size();
        double ahR = trueArr.isEmpty() ? Double.NaN : arrTp / (double) trueArr.size();

        return new double[]{adjP, adjR, adjF1, ahP, ahR};
    }

    private static Set<String> adjacencyKeys(Graph g) {
        Set<String> keys = new HashSet<>();
        for (Edge e : g.getEdges()) {
            String a = e.getNode1().getName();
            String b = e.getNode2().getName();
            keys.add(a.compareTo(b) < 0 ? a + "|" + b : b + "|" + a);
        }
        return keys;
    }

    /**
     * Directed endpoints: key "X->Y" for each edge X->Y in the (CPDAG-like) graph.
     */
    private static Set<String> arrowKeys(Graph g) {
        Set<String> keys = new HashSet<>();
        for (Edge e : g.getEdges()) {
            if (Edges.isDirectedEdge(e)) {
                Node tail = Edges.getDirectedEdgeTail(e);
                Node head = Edges.getDirectedEdgeHead(e);
                keys.add(tail.getName() + "->" + head.getName());
            }
        }
        return keys;
    }

    // ============================== simulation ==============================

    private record Sim(Graph dag, DataSet data) {
    }

    /**
     * Simulates a random DAG over mixed variables and data from it in the given regime.
     */
    private static Sim simulate(String regime, int nodes, int numEdges, double pDisc,
                                int levels, int n, double noiseSd, int seed) {
        Random rng = new Random(0xBF00F0L + 7919L * seed);

        // Variables: continuous by default; discrete with prob pDisc.
        List<Node> vars = new ArrayList<>();
        for (int i = 0; i < nodes; i++) {
            String name = "X" + (i + 1);
            if (rng.nextDouble() < pDisc) {
                vars.add(new DiscreteVariable(name, levels));
            } else {
                vars.add(new ContinuousVariable(name));
            }
        }

        Graph dag = RandomGraph.randomDag(vars, 0, numEdges, 100, 100, 100, false,
                0xDA6L + 104729L * seed);

        List<Node> order = topologicalOrder(dag);

        Map<Node, double[]> contVals = new HashMap<>();
        Map<Node, int[]> discVals = new HashMap<>();

        for (Node node : order) {
            List<Node> parents = dag.getParents(node);
            List<Node> contParents = new ArrayList<>();
            List<Node> discParents = new ArrayList<>();
            for (Node p : parents) {
                if (p instanceof DiscreteVariable) discParents.add(p);
                else contParents.add(p);
            }

            int dC = contParents.size();
            double[][] zc = new double[dC][];
            for (int j = 0; j < dC; j++) zc[j] = contVals.get(contParents.get(j));
            int[][] zd = new int[discParents.size()][];
            int[] card = new int[discParents.size()];
            for (int j = 0; j < discParents.size(); j++) {
                zd[j] = discVals.get(discParents.get(j));
                card[j] = ((DiscreteVariable) discParents.get(j)).getNumCategories();
            }
            int jointLevels = 1;
            for (int c : card) jointLevels = Math.min(64, jointLevels * c);

            if (node instanceof DiscreteVariable dv) {
                int L = dv.getNumCategories();
                double[][] u = new double[L][n]; // utilities
                if (parents.isEmpty()) {
                    int[] x = new int[n];
                    for (int i = 0; i < n; i++) x[i] = rng.nextInt(L);
                    discVals.put(node, x);
                } else {
                    for (int l = 0; l < L; l++) {
                        u[l] = systematic(regime, n, zc, zd, card, jointLevels, rng);
                        standardize(u[l]);
                    }
                    int[] x = new int[n];
                    for (int i = 0; i < n; i++) {
                        double max = Double.NEGATIVE_INFINITY;
                        for (int l = 0; l < L; l++) max = Math.max(max, u[l][i]);
                        double sum = 0;
                        double[] p = new double[L];
                        for (int l = 0; l < L; l++) {
                            p[l] = Math.exp(u[l][i] - max);
                            sum += p[l];
                        }
                        double r = rng.nextDouble() * sum, acc = 0;
                        int pick = L - 1;
                        for (int l = 0; l < L; l++) {
                            acc += p[l];
                            if (r <= acc) {
                                pick = l;
                                break;
                            }
                        }
                        x[i] = pick;
                    }
                    discVals.put(node, x);
                }
            } else {
                double[] x;
                if (parents.isEmpty()) {
                    x = new double[n];
                    for (int i = 0; i < n; i++) x[i] = rng.nextGaussian();
                } else {
                    double[] g = systematic(regime, n, zc, zd, card, jointLevels, rng);
                    standardize(g);
                    x = new double[n];
                    for (int i = 0; i < n; i++) x[i] = g[i] + noiseSd * rng.nextGaussian();
                }
                standardize(x);
                contVals.put(node, x);
            }
        }

        // Assemble mixed dataset in the original variable order.
        MixedDataBox box = new MixedDataBox(vars, n);
        DataSet data = new BoxDataSet(box, vars);
        for (int col = 0; col < vars.size(); col++) {
            Node v = vars.get(col);
            if (v instanceof DiscreteVariable) {
                int[] x = discVals.get(v);
                for (int i = 0; i < n; i++) data.setInt(i, col, x[i]);
            } else {
                double[] x = contVals.get(v);
                for (int i = 0; i < n; i++) data.setDouble(i, col, x[i]);
            }
        }

        return new Sim(dag, data);
    }

    /**
     * Systematic component g[i] for one equation (one continuous child, or one utility of a
     * discrete child), as a function of continuous parents zc and discrete parents zd.
     *
     * <p>POLY: sum over continuous parents of a1*z + a2*z^2, plus additive level offsets per
     * discrete parent. GP: RFF draw over continuous parents with a separate weight vector per
     * joint discrete level (interactionful); if no continuous parents, per-joint-level offsets.</p>
     */
    private static double[] systematic(String regime, int n, double[][] zc, int[][] zd,
                                       int[] card, int jointLevels, Random rng) {
        int dC = zc.length;
        double[] g = new double[n];

        if ("POLY".equalsIgnoreCase(regime)) {
            for (double[] z : zc) {
                double a1 = sign(rng) * (0.5 + 0.5 * rng.nextDouble());
                double a2 = sign(rng) * (0.3 + 0.4 * rng.nextDouble());
                for (int i = 0; i < n; i++) g[i] += a1 * z[i] + a2 * z[i] * z[i];
            }
            for (int j = 0; j < zd.length; j++) {
                double[] off = new double[card[j]];
                for (int l = 0; l < card[j]; l++) off[l] = rng.nextGaussian();
                for (int i = 0; i < n; i++) g[i] += off[zd[j][i]];
            }
            return g;
        }

        if ("GP".equalsIgnoreCase(regime)) {
            if (dC == 0) {
                // Purely discrete parents: independent offset per joint level.
                double[] off = new double[jointLevels];
                for (int l = 0; l < jointLevels; l++) off[l] = rng.nextGaussian();
                for (int i = 0; i < n; i++) g[i] = off[jointLevel(zd, card, i, jointLevels)];
                return g;
            }
            int m = 100;
            double ell = 0.7; // per-dimension RBF lengthscale on z-scored parents
            double[][] omega = new double[m][dC];
            double[] b = new double[m];
            for (int j = 0; j < m; j++) {
                for (int k = 0; k < dC; k++) omega[j][k] = rng.nextGaussian() / ell;
                b[j] = 2 * Math.PI * rng.nextDouble();
            }
            double[][] w = new double[jointLevels][m];
            for (int l = 0; l < jointLevels; l++)
                for (int j = 0; j < m; j++) w[l][j] = rng.nextGaussian();
            double scale = Math.sqrt(2.0 / m);
            for (int i = 0; i < n; i++) {
                int lvl = jointLevel(zd, card, i, jointLevels);
                double s = 0;
                for (int j = 0; j < m; j++) {
                    double dot = b[j];
                    for (int k = 0; k < dC; k++) dot += omega[j][k] * zc[k][i];
                    s += w[lvl][j] * Math.cos(dot);
                }
                g[i] = scale * s;
            }
            return g;
        }

        throw new IllegalArgumentException("Unknown regime: " + regime);
    }

    private static int jointLevel(int[][] zd, int[] card, int row, int jointLevels) {
        int idx = 0;
        for (int j = 0; j < zd.length; j++) idx = idx * card[j] + zd[j][row];
        return Math.floorMod(idx, jointLevels);
    }

    private static double sign(Random rng) {
        return rng.nextBoolean() ? 1.0 : -1.0;
    }

    private static void standardize(double[] x) {
        double mean = 0;
        for (double v : x) mean += v;
        mean /= x.length;
        double var = 0;
        for (double v : x) var += (v - mean) * (v - mean);
        var /= Math.max(1, x.length - 1);
        double sd = Math.sqrt(var);
        if (sd < 1e-12) sd = 1;
        for (int i = 0; i < x.length; i++) x[i] = (x[i] - mean) / sd;
    }

    private static List<Node> topologicalOrder(Graph dag) {
        List<Node> order = new ArrayList<>();
        Map<Node, Integer> inDeg = new LinkedHashMap<>();
        for (Node node : dag.getNodes()) inDeg.put(node, dag.getParents(node).size());
        List<Node> queue = new ArrayList<>();
        for (Map.Entry<Node, Integer> e : inDeg.entrySet())
            if (e.getValue() == 0) queue.add(e.getKey());
        while (!queue.isEmpty()) {
            Node node = queue.remove(0);
            order.add(node);
            for (Node c : dag.getChildren(node)) {
                int d = inDeg.get(c) - 1;
                inDeg.put(c, d);
                if (d == 0) queue.add(c);
            }
        }
        if (order.size() != dag.getNumNodes()) throw new IllegalStateException("Graph is cyclic?");
        return order;
    }

    // ============================== summary ==============================

    private static void printSummary(List<String> rows) {
        // group by regime|n|algo|params -> mean adjF1, mean ahP, mean ahR, mean elapsed
        // sums and counts per metric: [f1Sum, f1N, ahPSum, ahPN, ahRSum, ahRN, msSum, msN]
        Map<String, double[]> agg = new LinkedHashMap<>();
        for (String row : rows) {
            String[] f = row.split(",", -1);
            if (!"OK".equals(f[13])) continue;
            String key = f[0] + "|n=" + f[1] + "|" + f[3] + "|" + f[4];
            double[] s = agg.computeIfAbsent(key, k -> new double[8]);
            accum(s, 0, parse(f[9]));
            accum(s, 2, parse(f[10]));
            accum(s, 4, parse(f[11]));
            accum(s, 6, Double.parseDouble(f[12]));
        }
        System.out.println();
        System.out.println("# ===== Summary (means over seeds; OK rows only; NA skipped per metric) =====");
        System.out.printf(Locale.US, "# %-65s %8s %8s %8s %10s%n",
                "cell", "adjF1", "ahP", "ahR", "ms");
        for (Map.Entry<String, double[]> e : agg.entrySet()) {
            double[] s = e.getValue();
            System.out.printf(Locale.US, "# %-65s %8s %8s %8s %10s%n", e.getKey(),
                    mean(s, 0), mean(s, 2), mean(s, 4), mean(s, 6));
        }
    }

    private static void accum(double[] s, int i, double v) {
        if (!Double.isNaN(v)) {
            s[i] += v;
            s[i + 1] += 1;
        }
    }

    private static String mean(double[] s, int i) {
        return s[i + 1] == 0 ? "NA"
                : String.format(Locale.US, i == 6 ? "%.0f" : "%.4f", s[i] / s[i + 1]);
    }

    private static double parse(String s) {
        return "NA".equals(s) ? Double.NaN : Double.parseDouble(s);
    }

    // ============================== args ==============================

    private static Map<String, String> parseArgs(String[] args) {
        Map<String, String> m = new HashMap<>();
        for (String arg : args) {
            int eq = arg.indexOf('=');
            if (eq > 0) m.put(arg.substring(0, eq), arg.substring(eq + 1));
        }
        return m;
    }

    private static int intArg(Map<String, String> a, String k, int d) {
        return a.containsKey(k) ? Integer.parseInt(a.get(k)) : d;
    }

    private static double dblArg(Map<String, String> a, String k, double d) {
        return a.containsKey(k) ? Double.parseDouble(a.get(k)) : d;
    }

    private static boolean boolArg(Map<String, String> a, String k, boolean d) {
        return a.containsKey(k) ? Boolean.parseBoolean(a.get(k)) : d;
    }

    private static int[] intListArg(Map<String, String> a, String k, int[] d) {
        if (!a.containsKey(k)) return d;
        String[] parts = a.get(k).split(",");
        int[] out = new int[parts.length];
        for (int i = 0; i < parts.length; i++) out[i] = Integer.parseInt(parts[i].trim());
        return out;
    }

    private static double[] dblListArg(Map<String, String> a, String k, double[] d) {
        if (!a.containsKey(k)) return d;
        String[] parts = a.get(k).split(",");
        double[] out = new double[parts.length];
        for (int i = 0; i < parts.length; i++) out[i] = Double.parseDouble(parts[i].trim());
        return out;
    }

    private static String[] strListArg(Map<String, String> a, String k, String[] d) {
        if (!a.containsKey(k)) return d;
        String[] parts = a.get(k).split(",");
        for (int i = 0; i < parts.length; i++) parts[i] = parts[i].trim();
        return parts;
    }
}
