///////////////////////////////////////////////////////////////////////////////
// For information as to what this class does, see the Javadoc, below.       //
//                                                                           //
// Copyright (C) 2025 by Joseph Ramsey, Peter Spirtes, Clark Glymour,        //
// and Richard Scheines.                                                     //
//                                                                           //
// This program is free software: you can redistribute it and/or modify      //
// it under the terms of the GNU General Public License as published by      //
// the Free Software Foundation, either version 3 of the License, or         //
// (at your option) any later version.                                       //
//                                                                           //
// This program is distributed in the hope that it will be useful,           //
// but WITHOUT ANY WARRANTY; without even the implied warranty of            //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             //
// GNU General Public License for more details.                              //
//                                                                           //
// You should have received a copy of the GNU General Public License         //
// along with this program.  If not, see <https://www.gnu.org/licenses/>.    //
///////////////////////////////////////////////////////////////////////////////

package edu.cmu.tetradapp.editor;

import edu.cmu.tetrad.graph.EdgeListGraph;
import edu.cmu.tetrad.graph.Graph;
import edu.cmu.tetrad.graph.Node;
import edu.cmu.tetrad.graph.NodeType;
import edu.cmu.tetrad.search.utils.PagLegalityCheck;
import edu.cmu.tetradapp.util.GraphUtils;
import edu.cmu.tetradapp.util.WatchedProcess;
import edu.cmu.tetradapp.workbench.GraphWorkbench;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.util.HashSet;
import java.util.List;

/**
 * CheckGraphForMpdagAction is an action class that checks if a given graph is a legal MPDAG (Mixed Ancestral Graph) and
 * displays a message to indicate the result.
 */
public class CheckGraphForMagAction extends AbstractAction {

    /**
     * The desktop containing the target session editor.
     */
    private final GraphWorkbench workbench;

    /**
     * Stores the result of the legal MAG check.
     */
    private volatile PagLegalityCheck.LegalMagRet legalMag = null;

    /**
     * Highlights all latent variables in the given display graph.
     *
     * @param workbench the given workbench.
     */
    public CheckGraphForMagAction(GraphWorkbench workbench) {
        super("Check to see if Graph is a MAG");

        if (workbench == null) {
            throw new NullPointerException("Desktop must not be null.");
        }

        this.workbench = workbench;
    }

    /**
     * This method is used to perform an action when an event is triggered, specifically when the user clicks on a
     * button or menu item associated with it. It checks if a graph is a legal MAG (Mixed Ancestral Graph).
     *
     * @param e The ActionEvent object that represents the event generated by the user action.
     */
    public void actionPerformed(ActionEvent e) {
        Graph graph = workbench.getGraph();

        if (graph == null) {
            JOptionPane.showMessageDialog(GraphUtils.getContainingScrollPane(workbench), "No graph to check for MAGness.");
            return;
        }

        class MyWatchedProcess extends WatchedProcess {
            @Override
            public void watch() {
                List<Node> selection = graph.getNodes().stream()
                        .filter(node -> node.getNodeType() == NodeType.SELECTION).toList();

                Graph _graph = new EdgeListGraph(workbench.getGraph());
                legalMag = PagLegalityCheck.isLegalMag(_graph, new HashSet<>(selection));
            }
        }

        new MyWatchedProcess();

        while (legalMag == null) {
            try {
                Thread.sleep(100); // Sleep a bit to prevent tight loop
            } catch (InterruptedException e2) {
                Thread.currentThread().interrupt();
            }
        }

        String reason = GraphUtils.breakDown(legalMag.getReason(), 60);

        if (!legalMag.isLegalMag()) {
            JOptionPane.showMessageDialog(GraphUtils.getContainingScrollPane(workbench),
                    "This is not a legal MAG--one reason is as follows:" +
                    "\n\n" + reason + ".",
                    "Legal MAG check",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(GraphUtils.getContainingScrollPane(workbench), reason);
        }
    }
}




