///////////////////////////////////////////////////////////////////////////////
// For information as to what this class does, see the Javadoc, below.       //
//                                                                           //
// Copyright (C) 2025 by Joseph Ramsey, Peter Spirtes, Clark Glymour,        //
// and Richard Scheines.                                                     //
//                                                                           //
// This program is free software: you can redistribute it and/or modify      //
// it under the terms of the GNU General Public License as published by      //
// the Free Software Foundation, either version 3 of the License, or         //
// (at your option) any later version.                                       //
//                                                                           //
// This program is distributed in the hope that it will be useful,           //
// but WITHOUT ANY WARRANTY; without even the implied warranty of            //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             //
// GNU General Public License for more details.                              //
//                                                                           //
// You should have received a copy of the GNU General Public License         //
// along with this program.  If not, see <https://www.gnu.org/licenses/>.    //
///////////////////////////////////////////////////////////////////////////////

package edu.cmu.tetradapp.editor;

import edu.cmu.tetrad.data.DataModel;
import edu.cmu.tetrad.graph.Graph;
import edu.cmu.tetrad.search.test.CachedIndependenceQueries;
import edu.cmu.tetrad.search.test.MsepTest;
import edu.cmu.tetrad.util.JOptionUtils;
import edu.cmu.tetrad.util.Parameters;
import edu.cmu.tetradapp.util.DesktopController;
import edu.cmu.tetradapp.workbench.GraphWorkbench;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 * CheckGraphForCpdagAction is an action class that checks if a given graph is a legal CPDAG
 * (Completed Partially Directed Acyclic Graph) and displays a message to indicate the result.
 */
public class CheckIndependenceFacts extends AbstractAction {

    /**
     * The desktop containing the target session editor.
     */
    private ISelectedModel model;

    /**
     * Highlights all latent variables in the given display graph.
     *
     * @param model the given model.
     */
    public CheckIndependenceFacts(ISelectedModel model) {
        super("Check Independence Facts");

        if (model == null) {
            throw new NullPointerException("No selected model.");
        }

        this.model = model;
    }

    /**
     * This method is used to perform an action when an event is triggered, specifically when the user clicks on a button or menu item associated with it. It checks if a graph is
     *  a legal CPDAG (Completed Partially Directed Acyclic Graph).
     *
     * @param e The ActionEvent object that represents the event generated by the user action.
     */
    public void actionPerformed(ActionEvent e) {
        DataModel dataModel = model.getSelectedDataModel();
        IndependenceFactsDslEditor editor = new IndependenceFactsDslEditor(dataModel, new Parameters());
//        JOptionPane.showOptionDialog(JOptionUtils.centeringComp(), editor, "Independence Facts DSL Editor",
//                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, null, null);

        EditorWindow editorWindow = new EditorWindow(editor, "Nonlinearity Checks", null,
                false, JOptionUtils.centeringComp());

        DesktopController.getInstance().addEditorWindow(editorWindow, JLayeredPane.PALETTE_LAYER);
        editorWindow.pack();
        editorWindow.setVisible(true);
    }
}




