/// ////////////////////////////////////////////////////////////////////////////
// For information as to what this class does, see the Javadoc, below.       //
//                                                                           //
// Copyright (C) 2025 by Joseph Ramsey, Peter Spirtes, Clark Glymour,        //
// and Richard Scheines.                                                     //
//                                                                           //
// This program is free software: you can redistribute it and/or modify      //
// it under the terms of the GNU General Public License as published by      //
// the Free Software Foundation, either version 3 of the License, or         //
// (at your option) any later version.                                       //
//                                                                           //
// This program is distributed in the hope that it will be useful,           //
// but WITHOUT ANY WARRANTY; without even the implied warranty of            //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             //
// GNU General Public License for more details.                              //
//                                                                           //
// You should have received a copy of the GNU General Public License         //
// along with this program.  If not, see <https://www.gnu.org/licenses/>.    //
/// ////////////////////////////////////////////////////////////////////////////

package edu.cmu.tetrad.search;

import edu.cmu.tetrad.graph.*;
import edu.cmu.tetrad.search.test.CachingIndependenceTest;
import edu.cmu.tetrad.search.test.IndependenceTest;
import edu.cmu.tetrad.search.utils.SepsetProducer;
import edu.cmu.tetrad.search.utils.SepsetsMaxP;
import edu.cmu.tetrad.util.ChoiceGenerator;
import edu.cmu.tetrad.util.SublistGenerator;
import edu.cmu.tetrad.util.TetradLogger;

import java.util.*;

/**
 * Cyclic Causal Discovery (CCD) after Richardson.
 *
 * <p>Richardson, T. S. (2013). A discovery algorithm for directed cyclic graphs. arXiv:1302.3599.</p>
 * <p>See also Chapter 7 of: Glymour & Cooper (1999), <i>Computation, Causation, and Discovery</i>.</p>
 *
 * <p>Input: a conditional independence oracle/test for continuous data possibly generated by a directed cyclic model.
 * Output: a cyclic PAG (with underline/dotted-underline annotations) representing the Markov equivalence class of the
 * true DCG.</p>
 *
 * <p>Note: This class does not respect background knowledge.</p>
 */
public final class Ccd implements IGraphSearch {

    /** The nodes (fixed ordering) */
    private final List<Node> nodes;

    /** Cached independence test */
    private IndependenceTest test;

    /** Whether to apply Richardson's R1 push-away rule during propagation (default: true). */
    private boolean applyR1 = true;

    /** Verbose logging toggle. */
    private boolean verbose;

    /** Maximum conditioning depth; -1 means unlimited. */
    private int depth = -1;

    /**
     * Construct CCD with the given test.
     */
    public Ccd(IndependenceTest test) {
        if (test == null) throw new NullPointerException("Test is not provided");
        // Always wrap in cache to avoid performance regressions.
        this.test = (test instanceof CachingIndependenceTest) ? test : new CachingIndependenceTest(test);
        this.nodes = this.test.getVariables();
    }

    /**
     * Run CCD and return a cyclic PAG.
     */
    public Graph search() throws InterruptedException {
        Map<Triple, Set<Node>> supSepsets = new HashMap<>();

        if (verbose) TetradLogger.getInstance().log("CCD: Step A — Fast Adjacency Search (FAS)");

        Fas fas = new Fas(this.test);
        Graph psi = fas.search();
        psi.reorientAllWith(Endpoint.CIRCLE);

        // Prefer Max-P sepset producer over stored FAS sepsets for stability and depth control.
        SepsetProducer sepsets = new SepsetsMaxP(psi, test, depth);

        stepB(psi, sepsets);
        stepC(psi, sepsets);
        stepD(psi, sepsets, supSepsets);
        stepE(supSepsets, psi);
        stepF(psi, sepsets, supSepsets);

        orientAwayFromArrow(psi);

        return psi;
    }

    public IndependenceTest getTest() { return test; }

    /**
     * Replace the test, preserving caching and requiring identical variable sets (order-insensitive).
     */
    public void setTest(IndependenceTest test) {
        Objects.requireNonNull(test, "test");
        Set<Node> oldSet = new HashSet<>(this.test.getVariables());
        Set<Node> newSet = new HashSet<>(test.getVariables());
        if (!oldSet.equals(newSet)) {
            throw new IllegalArgumentException("New test must have the same variable set as the existing test.");
        }
        this.test = (test instanceof CachingIndependenceTest) ? test : new CachingIndependenceTest(test);
    }

    public boolean isApplyR1() { return this.applyR1; }
    public void setApplyR1(boolean applyR1) { this.applyR1 = applyR1; }

    public void setVerbose(boolean verbose) {
        this.verbose = verbose;
        test.setVerbose(verbose);
    }

    public void setDepth(int depth) { this.depth = depth; }

    // ====== Algorithm Steps ===================================================

    /**
     * Step B — Add underlines (non-colliders) and colliders for unshielded triples.
     */
    private void stepB(Graph psi, SepsetProducer sepsets) throws InterruptedException {
        if (verbose) TetradLogger.getInstance().log("CCD: Step B — Underlines & Colliders");

        for (Node b : this.nodes) {
            if (Thread.currentThread().isInterrupted()) throw new InterruptedException();

            List<Node> adj = new ArrayList<>(psi.getAdjacentNodes(b));
            if (adj.size() < 2) continue;

            ChoiceGenerator cg = new ChoiceGenerator(adj.size(), 2);
            int[] idx;
            while ((idx = cg.next()) != null) {
                if (Thread.currentThread().isInterrupted()) throw new InterruptedException();

                Node a = adj.get(idx[0]);
                Node c = adj.get(idx[1]);

                // Only unshielded triples
                if (psi.isAdjacentTo(a, c)) continue;

                Set<Node> S = sepsets.getSepset(a, c, -1, null);
                if (S == null) continue;

                if (S.contains(b)) {
                    // non-collider at b
                    psi.addUnderlineTriple(a, b, c);
                    if (verbose)
                        TetradLogger.getInstance().log("StepB: underline (non-collider) " + a + "-" + b + "-" + c + " ; S(a,c)=" + S);
                } else {
                    // collider at b
                    psi.removeEdge(a, b);
                    psi.removeEdge(c, b);
                    psi.addDirectedEdge(a, b);
                    psi.addDirectedEdge(c, b);
                    if (verbose)
                        TetradLogger.getInstance().log("StepB: collider " + a + "->" + b + "<-" + c + " ; S(a,c)=" + S);
                }
            }
        }
    }

    /**
     * Step C — Propagate some orientations (with change-flag until quiescence).
     */
    private void stepC(Graph psi, SepsetProducer sepsets) throws InterruptedException {
        if (verbose) TetradLogger.getInstance().log("CCD: Step C — Orientation propagation");

        boolean changed;
        do {
            if (Thread.currentThread().isInterrupted()) throw new InterruptedException();
            changed = false;

            for (Edge edge : new ArrayList<>(psi.getEdges())) {
                if (Thread.currentThread().isInterrupted()) throw new InterruptedException();

                Node x = edge.getNode1();
                Node y = edge.getNode2();

                List<Node> adjx = psi.getAdjacentNodes(x);
                List<Node> adjy = psi.getAdjacentNodes(y);

                // Skip if some node->x and underline(y, x, node)
                boolean skip = false;
                for (Node node : new ArrayList<>(adjx)) {
                    Edge ex = psi.getEdge(node, x);
                    if (ex != null && ex.getProximalEndpoint(x) == Endpoint.ARROW && psi.isUnderlineTriple(y, x, node)) {
                        skip = true;
                        break;
                    }
                }
                if (skip) continue;

                for (Node a : this.nodes) {
                    if (a == x || a == y) continue;
                    if (adjx.contains(a) || adjy.contains(a)) continue;

                    // Orientable? require o? at y-x side
                    if (!(psi.getEndpoint(y, x) == Endpoint.CIRCLE &&
                          (psi.getEndpoint(x, y) == Endpoint.CIRCLE || psi.getEndpoint(x, y) == Endpoint.TAIL))) {
                        continue;
                    }

                    Set<Node> sepset = sepsets.getSepset(a, y, -1, null);
                    if (sepset == null) continue;
                    if (sepset.contains(x)) continue;

                    if (!sepsets.isIndependent(a, x, new HashSet<>(sepset))) {
                        // Orient y -> x
                        psi.removeEdge(x, y);
                        psi.addDirectedEdge(y, x);
                        orientAwayFromArrow(y, x, psi);
                        changed = true;
                        break;
                    }
                }
            }
        } while (changed);
    }

    /**
     * Step D — Add dotted-underline triples and compute supSepsets.
     */
    private void stepD(Graph psi, SepsetProducer sepsets, Map<Triple, Set<Node>> supSepsets) throws InterruptedException {
        if (verbose) TetradLogger.getInstance().log("CCD: Step D — Dotted underlines");

        Map<Node, List<Node>> local = new HashMap<>();
        for (Node node : psi.getNodes()) {
            if (Thread.currentThread().isInterrupted()) throw new InterruptedException();
            local.put(node, local(psi, node));
        }

        for (Node node : this.nodes) {
            if (Thread.currentThread().isInterrupted()) throw new InterruptedException();
            doNodeStepD(psi, sepsets, supSepsets, local, node);
        }
    }

    private void doNodeStepD(Graph psi, SepsetProducer sepsets, Map<Triple, Set<Node>> supSepsets,
                             Map<Node, List<Node>> local, Node b) throws InterruptedException {
        List<Node> adj = new ArrayList<>(psi.getAdjacentNodes(b));
        if (adj.size() < 2) return;

        ChoiceGenerator gen = new ChoiceGenerator(adj.size(), 2);
        int[] choice;

        while ((choice = gen.next()) != null) {
            if (Thread.currentThread().isInterrupted()) throw new InterruptedException();

            List<Node> _adj = GraphUtils.asList(choice, adj);
            Node a = _adj.get(0);
            Node c = _adj.get(1);

            if (!psi.isDefCollider(a, b, c)) continue;

            Set<Node> S = sepsets.getSepset(a, c, -1, null);
            if (S == null) continue;

            ArrayList<Node> TT = new ArrayList<>(local.getOrDefault(a, Collections.emptyList()));
            TT.removeAll(S);
            TT.remove(b);
            TT.remove(c);

            int kMax = (depth < 0) ? -1 : Math.min(depth, TT.size());
            SublistGenerator gen2 = new SublistGenerator(TT.size(), kMax);
            int[] choice2;

            while ((choice2 = gen2.next()) != null) {
                if (Thread.currentThread().isInterrupted()) throw new InterruptedException();

                Set<Node> T = GraphUtils.asSet(choice2, TT);
                Set<Node> B = new HashSet<>(T);
                B.addAll(S);
                B.add(b);

                if (sepsets.isIndependent(a, c, new HashSet<>(B))) {
                    psi.addDottedUnderlineTriple(a, b, c);
                    supSepsets.put(new Triple(a, b, c), B);
                    break;
                }
            }
        }
    }

    /**
     * Step E — Use supSepsets to orient edges out of b towards neighbors in A∪C neighborhoods.
     */
    private void stepE(Map<Triple, Set<Node>> supSepset, Graph psi) throws InterruptedException {
        if (verbose) TetradLogger.getInstance().log("CCD: Step E — Orientation propagation via supSepsets");

        for (Triple triple : new ArrayList<>(psi.getDottedUnderlines())) {
            if (Thread.currentThread().isInterrupted()) throw new InterruptedException();

            Set<Node> sup = supSepset.get(triple);
            if (sup == null) continue;

            Node a = triple.getX();
            Node b = triple.getY();
            Node c = triple.getZ();

            // For neighbors of a
            for (Node d : new ArrayList<>(psi.getAdjacentNodes(a))) {
                if (d == b) continue;
                if (psi.getEndpoint(b, d) != Endpoint.CIRCLE) continue;

                if (sup.contains(d)) {
                    psi.setEndpoint(b, d, Endpoint.TAIL);
                } else if (psi.getEndpoint(d, b) != Endpoint.ARROW) {
                    psi.removeEdge(b, d);
                    psi.addDirectedEdge(b, d);
                    orientAwayFromArrow(b, d, psi);
                }
            }

            // For neighbors of c
            for (Node d : new ArrayList<>(psi.getAdjacentNodes(c))) {
                if (d == b) continue;
                if (psi.getEndpoint(b, d) != Endpoint.CIRCLE) continue;

                if (sup.contains(d)) {
                    psi.setEndpoint(b, d, Endpoint.TAIL);
                } else if (psi.getEndpoint(d, b) != Endpoint.ARROW) {
                    psi.removeEdge(b, d);
                    psi.addDirectedEdge(b, d);
                    orientAwayFromArrow(b, d, psi);
                }
            }
        }
    }

    /**
     * Step F — Further propagation using d-connection given supSepset ∪ {d}.
     */
    private void stepF(Graph psi, SepsetProducer sepsets, Map<Triple, Set<Node>> supSepsets) throws InterruptedException {
        if (verbose) TetradLogger.getInstance().log("CCD: Step F — More orientations via d-connection checks");

        for (Triple triple : new ArrayList<>(psi.getDottedUnderlines())) {
            if (Thread.currentThread().isInterrupted()) throw new InterruptedException();

            Node a = triple.getX();
            Node b = triple.getY();
            Node c = triple.getZ();

            Set<Node> sup = supSepsets.get(triple);
            if (sup == null) continue;

            Set<Node> adj = new HashSet<>(psi.getAdjacentNodes(a));
            adj.addAll(psi.getAdjacentNodes(c));

            for (Node d : new ArrayList<>(adj)) {
                if (Thread.currentThread().isInterrupted()) throw new InterruptedException();

                if (psi.getEndpoint(b, d) != Endpoint.CIRCLE) continue;
                if (psi.getEndpoint(d, b) == Endpoint.ARROW) continue;
                if (psi.isAdjacentTo(a, d) && psi.isAdjacentTo(c, d)) continue;
                if (!psi.isAdjacentTo(b, d)) continue;

                Set<Node> supSepUnionD = new HashSet<>(sup);
                supSepUnionD.add(d);

                if (!sepsets.isIndependent(a, c, new HashSet<>(supSepUnionD))) {
                    psi.removeEdge(b, d);
                    psi.addDirectedEdge(b, d);
                    orientAwayFromArrow(b, d, psi);
                }
            }
        }
    }

    // ====== Helpers ===========================================================

    /**
     * Local expansion around x: adj(x) plus any z adjacent to some y∈adj(x) with x-y-z a definite collider.
     */
    private List<Node> local(Graph psi, Node x) {
        Set<Node> nodes = new HashSet<>(psi.getAdjacentNodes(x));
        for (Node y : new HashSet<>(nodes)) {
            for (Node z : psi.getAdjacentNodes(y)) {
                if (psi.isDefCollider(x, y, z) && z != x) {
                    nodes.add(z);
                }
            }
        }
        return new ArrayList<>(nodes);
    }

    /** Top-level push-away pass over all arrowheads (iterate over snapshot). */
    private void orientAwayFromArrow(Graph graph) throws InterruptedException {
        for (Edge e : new ArrayList<>(graph.getEdges())) {
            if (Thread.currentThread().isInterrupted()) throw new InterruptedException();

            Node n1 = e.getNode1();
            Node n2 = e.getNode2();
            Edge cur = graph.getEdge(n1, n2);
            if (cur == null) continue;

            if (cur.pointsTowards(n1)) {
                orientAwayFromArrow(n2, n1, graph);
            } else if (cur.pointsTowards(n2)) {
                orientAwayFromArrow(n1, n2, graph);
            }
        }
    }

    /** Apply R1 push-away from a->b to b's nondirected neighbors, recursively. */
    private void orientAwayFromArrow(Node a, Node b, Graph graph) {
        if (!isApplyR1()) return;
        for (Node c : new ArrayList<>(graph.getAdjacentNodes(b))) {
            if (c == a) continue;
            orientAwayFromArrowVisit(a, b, c, graph);
        }
    }

    /** DFS-style push-away with backtracking safety. */
    private boolean orientAwayFromArrowVisit(Node a, Node b, Node c, Graph graph) {
        Edge bc = graph.getEdge(b, c);
        if (bc == null || !Edges.isNondirectedEdge(bc)) return false;
        if (!graph.isUnderlineTriple(a, b, c)) return false;
        if (bc.pointsTowards(b)) return false;

        graph.removeEdge(b, c);
        graph.addDirectedEdge(b, c);

        for (Node d : new ArrayList<>(graph.getAdjacentNodes(c))) {
            if (d == b) return true;
            Edge cur = graph.getEdge(b, c);
            if (cur == null) return true; // edge removed elsewhere
            if (!orientAwayFromArrowVisit(b, c, d, graph)) {
                graph.removeEdge(b, c);
                graph.addEdge(cur);
            }
        }
        return true;
    }
}