/// ////////////////////////////////////////////////////////////////////////////
// For information as to what this class does, see the Javadoc, below.       //
//                                                                           //
// Copyright (C) 2025 by Joseph Ramsey, Peter Spirtes, Clark Glymour,        //
// and Richard Scheines.                                                     //
//                                                                           //
// This program is free software: you can redistribute it and/or modify      //
// it under the terms of the GNU General Public License as published by      //
// the Free Software Foundation, either version 3 of the License, or         //
// (at your option) any later version.                                       //
//                                                                           //
// This program is distributed in the hope that it will be useful,           //
// but WITHOUT ANY WARRANTY; without even the implied warranty of            //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             //
// GNU General Public License for more details.                              //
//                                                                           //
// You should have received a copy of the GNU General Public License         //
// along with this program.  If not, see <https://www.gnu.org/licenses/>.    //
/// ////////////////////////////////////////////////////////////////////////////

package edu.cmu.tetrad.search;

import edu.cmu.tetrad.data.CovarianceMatrix;
import edu.cmu.tetrad.data.DataSet;
import edu.cmu.tetrad.data.ICovarianceMatrix;
import edu.cmu.tetrad.graph.Edge;
import edu.cmu.tetrad.graph.EdgeListGraph;
import edu.cmu.tetrad.graph.Edges;
import edu.cmu.tetrad.graph.Graph;
import edu.cmu.tetrad.graph.Node;
import edu.cmu.tetrad.search.utils.MeekRules;
import edu.cmu.tetrad.util.Matrix;
import edu.cmu.tetrad.util.RandomUtil;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Implements the <i>G-regression</i> estimator of Guo and Perković (2022) for total causal effects under
 * linearity and causal sufficiency, given an MPDAG.
 * <p>
 * Setting. The data are assumed to be generated by a recursive linear structural equation model (SEM) with
 * independent (not necessarily Gaussian) errors, whose causal DAG D is known only up to a maximally oriented
 * PDAG (MPDAG) G, i.e., D is one of the DAGs represented by G. An MPDAG is a PDAG (directed and undirected
 * edges, no directed cycles) that is closed under Meek's orientation rules R1-R4; DAGs and CPDAGs are special
 * cases, and so is a CPDAG augmented with background knowledge via Meek's rules.
 * <p>
 * Given a treatment set A (a single variable, or several variables for a joint intervention) and an outcome Y
 * not in A, the total effect tau_AY is the gradient of E[Y | do(X_A = x_A)] with respect to x_A. It is
 * identified from G if and only if there is no proper possibly causal path from A to Y in G that starts with an
 * undirected edge (Perković, 2020, Proposition 3.2; Theorem 2 of Guo and Perković, 2022).
 * <p>
 * Estimator. Let B_1, ..., B_K be the <i>buckets</i> of G, the connected components of the undirected part of
 * G. By Meek closure, all vertices in a bucket share the same set of external parents, Pa(B_k) (the "restrictive
 * property", Corollary 4 of the paper). For each bucket with nonempty Pa(B_k), G-regression regresses each
 * X_j, j in B_k, on X_{Pa(B_k)} by ordinary least squares, giving a coefficient block
 * Lambda_k = Sigma_{Pa(B_k)}^{-1} Sigma_{Pa(B_k), B_k} (Eq. 18); all other entries of Lambda are zero. Then, with
 * D = An(Y, G_{V \ A}) the ancestors of Y in the induced subgraph on V \ A, the estimate is (Eq. 19)
 * <pre>
 *     tau_AY = Lambda_{A,D} [ (I - Lambda_{D,D})^{-1} ]_{D,Y}.
 * </pre>
 * Theorem 15 of the paper shows that this estimator has the smallest asymptotic covariance among all consistent,
 * differentiable functions of the sample covariance, a class that includes covariate adjustment (including the
 * optimal adjustment set of Henckel et al., 2022) and the joint-IDA estimators of Nandy et al. (2017). It exists
 * for every identified effect, point or joint, whereas adjustment and joint-IDA estimators need not.
 * <p>
 * This class is a pure function of (MPDAG, covariance matrix). The graph is validated in the constructor: it
 * must contain only directed and undirected edges, be acyclic, and be closed under Meek's rules; an
 * IllegalArgumentException is thrown otherwise. Callers wanting to incorporate background knowledge into a CPDAG
 * should do so with {@link MeekRules} before constructing this object. Graph nodes and covariance variables are
 * matched by name.
 * <p>
 * The identification check follows Theorem 2 exactly (with "possibly causal" in the strong sense of Perković et
 * al., 2017, Definition 3.1: no edge v_l &lt;- v_r for any l &lt; r on the path). For each a in A and each
 * undirected neighbor u of a not in A, we ask whether there is a possibly causal path from u to Y in the
 * induced subgraph on V \ (A ∪ Pa(a, G)). Excluding A makes the path proper; excluding Pa(a) rules out
 * a &lt;- v_r. That subgraph is itself an MPDAG, so by Lemmas 3.5 and 3.6 of Perković et al. (2017) such a path
 * exists iff an <i>unshielded</i> path with no edge v_i &lt;- v_{i+1} exists, which is found by a breadth-first
 * search over (previous, current) vertex pairs.
 * <p>
 * References:
 * <ul>
 * <li>Guo, F. R., and Perković, E. (2022). Efficient least squares for estimating total effects under linearity
 * and causal sufficiency. Journal of Machine Learning Research, 23(104), 1-41.</li>
 * <li>Perković, E. (2020). Identifying causal effects in maximally oriented partially directed acyclic graphs.
 * UAI 2020.</li>
 * <li>Perković, E., Kalisch, M., and Maathuis, M. H. (2017). Interpreting and using CPDAGs with background
 * knowledge. UAI 2017.</li>
 * </ul>
 *
 * @author josephramsey
 * @see Ida
 * @see MeekRules
 */
public final class GRegression {

    /**
     * The validated MPDAG.
     */
    private final Graph graph;
    /**
     * The sample (or population) covariance matrix.
     */
    private final ICovarianceMatrix cov;
    /**
     * Graph nodes in covariance-variable order.
     */
    private final List<Node> nodes;
    /**
     * Graph node to covariance index.
     */
    private final Map<Node, Integer> index = new HashMap<>();
    /**
     * Bucket decomposition of the MPDAG (connected components of the undirected subgraph).
     */
    private final List<Set<Node>> buckets;
    /**
     * The block-recursive coefficient matrix Lambda (Proposition 7 / Lemma 11); lambda[i][j] is the coefficient of
     * X_i in the regression of X_j on X_{Pa(B(j))}, and zero unless i is an external parent of j's bucket.
     */
    private final Matrix lambda;

    /**
     * Constructs a G-regression estimator for the given MPDAG and covariance matrix.
     *
     * @param mpdag A graph containing only directed and undirected edges, acyclic, and closed under Meek's rules
     *              R1-R4 (a DAG, a CPDAG, or a CPDAG with background knowledge incorporated via Meek's rules).
     * @param cov   A covariance matrix over the same variables (matched by name).
     * @throws IllegalArgumentException if the graph is not an MPDAG or the variables do not match.
     */
    public GRegression(Graph mpdag, ICovarianceMatrix cov) {
        if (mpdag == null) throw new IllegalArgumentException("Graph is null.");
        if (cov == null) throw new IllegalArgumentException("Covariance matrix is null.");

        String problem = mpdagProblem(mpdag);
        if (problem != null) {
            throw new IllegalArgumentException("Graph is not an MPDAG: " + problem);
        }

        this.graph = mpdag;
        this.cov = cov;

        List<Node> covVars = cov.getVariables();
        this.nodes = new ArrayList<>(covVars.size());

        for (int i = 0; i < covVars.size(); i++) {
            Node covVar = covVars.get(i);
            Node graphNode = mpdag.getNode(covVar.getName());

            if (graphNode == null) {
                throw new IllegalArgumentException("Covariance variable " + covVar.getName()
                                                   + " is not a node in the graph.");
            }

            this.nodes.add(graphNode);
            this.index.put(graphNode, i);
        }

        if (this.index.size() != mpdag.getNumNodes()) {
            throw new IllegalArgumentException("The graph has nodes that are not covariance variables.");
        }

        this.buckets = bucketDecomposition(mpdag);
        this.lambda = computeLambda();
    }

    // -------------------------------------------------------------------------------------------------------------
    // Graph structure.
    // -------------------------------------------------------------------------------------------------------------

    /**
     * Returns null if the graph is an MPDAG, or else a description of why it is not. An MPDAG contains only
     * directed and undirected edges, has no directed cycle, and is closed under Meek's rules R1-R4.
     *
     * @param graph The graph.
     * @return null if the graph is an MPDAG; otherwise a reason.
     */
    public static String mpdagProblem(Graph graph) {
        for (Edge edge : graph.getEdges()) {
            if (!(Edges.isDirectedEdge(edge) || Edges.isUndirectedEdge(edge))) {
                return "edge " + edge + " is neither directed nor undirected.";
            }
        }

        if (graph.paths().existsDirectedCycle()) {
            return "the graph contains a directed cycle.";
        }

        Graph closed = new EdgeListGraph(graph);
        MeekRules meek = new MeekRules();
        meek.setRevertToUnshieldedColliders(false);
        meek.setVerbose(false);
        meek.orientImplied(closed);

        Set<Edge> before = graph.getEdges();
        Set<Edge> after = closed.getEdges();

        if (!before.equals(after)) {
            Set<Edge> changed = new LinkedHashSet<>(after);
            changed.removeAll(before);
            return "the graph is not closed under Meek's rules; e.g., Meek's rules orient " + changed;
        }

        return null;
    }

    /**
     * Returns true if the graph is an MPDAG (only directed and undirected edges, acyclic, and closed under Meek's
     * rules R1-R4).
     *
     * @param graph The graph.
     * @return True if the graph is an MPDAG.
     */
    public static boolean isMpdag(Graph graph) {
        return mpdagProblem(graph) == null;
    }

    /**
     * Returns the bucket decomposition of the graph: the maximal connected components of its undirected subgraph
     * (Section 3.4.1 of Guo and Perković, 2022). Every node belongs to exactly one bucket; a node with no undirected
     * edges is a singleton bucket. The order of the returned list is arbitrary (the estimator does not depend on a
     * partial causal ordering of the buckets).
     *
     * @param graph A PDAG.
     * @return The list of buckets.
     */
    public static List<Set<Node>> bucketDecomposition(Graph graph) {
        List<Set<Node>> buckets = new ArrayList<>();
        Set<Node> seen = new HashSet<>();

        for (Node start : graph.getNodes()) {
            if (seen.contains(start)) continue;

            Set<Node> bucket = new LinkedHashSet<>();
            Deque<Node> queue = new ArrayDeque<>();
            queue.add(start);
            seen.add(start);

            while (!queue.isEmpty()) {
                Node x = queue.remove();
                bucket.add(x);

                for (Node y : graph.getAdjacentNodes(x)) {
                    if (seen.contains(y)) continue;
                    Edge edge = graph.getEdge(x, y);
                    if (edge != null && Edges.isUndirectedEdge(edge)) {
                        seen.add(y);
                        queue.add(y);
                    }
                }
            }

            buckets.add(bucket);
        }

        return buckets;
    }

    /**
     * Returns the external parents of a set of nodes: the union of their parents, minus the set itself.
     *
     * @param graph The graph.
     * @param set   The set of nodes.
     * @return Pa(set) = (union of Pa(i) for i in set) \ set.
     */
    public static Set<Node> externalParents(Graph graph, Collection<Node> set) {
        Set<Node> parents = new LinkedHashSet<>();
        for (Node x : set) parents.addAll(graph.getParents(x));
        parents.removeAll(set);
        return parents;
    }

    /**
     * Checks the restrictive property (Corollary 4 of Guo and Perković, 2022) for a bucket: every node in the
     * bucket has the same set of external parents. This holds for every bucket of an MPDAG; it is exposed for
     * testing and diagnostics.
     *
     * @param graph  The graph.
     * @param bucket The bucket.
     * @return True if Pa(bucket) = Pa(i) \ bucket for every i in the bucket.
     */
    public static boolean hasRestrictiveProperty(Graph graph, Set<Node> bucket) {
        Set<Node> bucketParents = externalParents(graph, bucket);

        for (Node x : bucket) {
            Set<Node> paX = new HashSet<>(graph.getParents(x));
            paX.removeAll(bucket);
            if (!paX.equals(bucketParents)) return false;
        }

        return true;
    }

    /**
     * Returns the ancestors of y in the subgraph of the graph induced by V \ excluded, i.e., the set of nodes from
     * which y is reachable by a directed path all of whose vertices lie outside the excluded set. By convention y
     * is an ancestor of itself (and must not be excluded).
     *
     * @param graph    The graph.
     * @param y        The node.
     * @param excluded Nodes to remove from the graph before computing ancestors.
     * @return An(y, G_{V \ excluded}).
     */
    public static Set<Node> ancestorsAvoiding(Graph graph, Node y, Set<Node> excluded) {
        if (excluded.contains(y)) throw new IllegalArgumentException("Outcome may not be excluded.");

        Set<Node> ancestors = new LinkedHashSet<>();
        Deque<Node> queue = new ArrayDeque<>();
        queue.add(y);
        ancestors.add(y);

        while (!queue.isEmpty()) {
            Node x = queue.remove();

            for (Node w : graph.getParents(x)) {
                if (excluded.contains(w) || ancestors.contains(w)) continue;
                ancestors.add(w);
                queue.add(w);
            }
        }

        return ancestors;
    }

    /**
     * Determines whether the total effect of the treatments on the outcome is identified given the MPDAG,
     * according to Theorem 2 of Guo and Perković (2022) (Perković, 2020, Proposition 3.2): the effect is identified
     * if and only if there is no proper possibly causal path from the treatment set to the outcome that starts with
     * an undirected edge.
     * <p>
     * "Possibly causal" is meant in the strong sense of Perković et al. (2017), Definition 3.1, and the check is
     * exact; see the class documentation for the reduction to an unshielded-path search.
     *
     * @param mpdag      An MPDAG. (Not re-validated here; use the constructor or {@link #isMpdag(Graph)}.)
     * @param treatments The treatment set A (nonempty).
     * @param outcome    The outcome Y, not in A.
     * @return True if tau_AY is identified from the MPDAG.
     */
    public static boolean isIdentified(Graph mpdag, Set<Node> treatments, Node outcome) {
        return nonIdentificationWitness(mpdag, treatments, outcome) == null;
    }

    /**
     * Returns a witness to non-identification, if any: a proper possibly causal path from a treatment to the
     * outcome that starts with an undirected edge (Theorem 2). Returns null if the effect is identified.
     * <p>
     * The path is returned as a list of nodes beginning with the treatment and ending with the outcome. Its first
     * edge is undirected, and its orientation is the piece of information the MPDAG is missing: if that edge were
     * oriented away from the treatment the path would be causal, and if toward the treatment it would not be, so
     * the DAGs in the class disagree about the effect. Supplying that orientation as background knowledge (and
     * Meek-closing) is therefore the natural way to make progress. The returned path is unshielded and is the
     * shortest such path found by breadth-first search from the first treatment/neighbor pair that yields one.
     *
     * @param mpdag      An MPDAG. (Not re-validated here; use the constructor or {@link #isMpdag(Graph)}.)
     * @param treatments The treatment set A (nonempty).
     * @param outcome    The outcome Y, not in A.
     * @return A witness path, or null if tau_AY is identified from the MPDAG.
     */
    public static List<Node> nonIdentificationWitness(Graph mpdag, Set<Node> treatments, Node outcome) {
        if (treatments == null || treatments.isEmpty()) {
            throw new IllegalArgumentException("Treatment set is empty.");
        }
        if (treatments.contains(outcome)) {
            throw new IllegalArgumentException("Outcome must not be a treatment.");
        }

        for (Node a : treatments) {
            Set<Node> forbidden = new HashSet<>(treatments);
            forbidden.addAll(mpdag.getParents(a));

            for (Node u : mpdag.getAdjacentNodes(a)) {
                if (treatments.contains(u)) continue;
                Edge edge = mpdag.getEdge(a, u);
                if (edge == null || !Edges.isUndirectedEdge(edge)) continue;

                // Now a - u is the first edge; ask whether it can be continued to a possibly causal path to
                // the outcome avoiding A and Pa(a).
                List<Node> rest = unshieldedPossiblyCausalPath(mpdag, u, outcome, forbidden);

                if (rest != null) {
                    List<Node> path = new ArrayList<>(rest.size() + 1);
                    path.add(a);
                    path.addAll(rest);
                    return path;
                }
            }
        }

        return null;
    }

    /**
     * Renders a path as a string using the graph's edge marks, e.g. "X2 --- X3 --- X4 --> X5".
     *
     * @param graph The graph.
     * @param path  A path in the graph.
     * @return The rendered path.
     */
    public static String pathString(Graph graph, List<Node> path) {
        StringBuilder sb = new StringBuilder();

        for (int i = 0; i < path.size(); i++) {
            if (i > 0) {
                // Look nodes up by name so that a path from an equivalent copy of the graph still renders.
                Node prev = graph.getNode(path.get(i - 1).getName());
                Node cur = graph.getNode(path.get(i).getName());
                Edge e = (prev == null || cur == null) ? null : graph.getEdge(prev, cur);
                if (e == null) sb.append(" ... ");
                else if (Edges.isUndirectedEdge(e)) sb.append(" --- ");
                else if (Edges.getDirectedEdgeHead(e) == cur) sb.append(" --> ");
                else sb.append(" <-- ");
            }
            sb.append(path.get(i).getName());
        }

        return sb.toString();
    }

    /**
     * Breadth-first search for an unshielded path from 'from' to 'to' in the subgraph induced on V \ forbidden,
     * every edge of which is of the form v_i -&gt; v_{i+1} or v_i - v_{i+1}. In an MPDAG, such a path exists iff a
     * possibly causal path (in the strong sense) from 'from' to 'to' exists (Perković et al., 2017, Lemmas 3.5
     * and 3.6). The state of the search is the pair (previous, current), since unshieldedness is a property of
     * consecutive triples. (In an MPDAG such a walk cannot revisit a vertex, since the undirected part of every
     * bucket is chordal and directed edges only lead forward in the bucket ordering; so the walk found is a path.)
     */
    private static List<Node> unshieldedPossiblyCausalPath(Graph g, Node from, Node to, Set<Node> forbidden) {
        if (forbidden.contains(from) || forbidden.contains(to)) return null;
        if (from == to) return List.of(from);

        // Each state is (previous, current); 'parent' records the state we came from so the path can be rebuilt.
        Map<List<Node>, List<Node>> parent = new HashMap<>();
        Deque<List<Node>> queue = new ArrayDeque<>();

        for (Node w : g.getAdjacentNodes(from)) {
            if (forbidden.contains(w)) continue;
            if (!leadsForward(g, from, w)) continue;
            List<Node> state = List.of(from, w);
            if (w == to) return List.of(from, w);
            if (!parent.containsKey(state)) {
                parent.put(state, null);
                queue.add(state);
            }
        }

        while (!queue.isEmpty()) {
            List<Node> state = queue.remove();
            Node prev = state.get(0);
            Node cur = state.get(1);

            for (Node w : g.getAdjacentNodes(cur)) {
                if (w == prev || forbidden.contains(w)) continue;
                if (g.isAdjacentTo(prev, w)) continue;          // keep the path unshielded
                if (!leadsForward(g, cur, w)) continue;         // cur -> w or cur - w only
                List<Node> next = List.of(cur, w);
                if (parent.containsKey(next)) continue;
                parent.put(next, state);

                if (w == to) {
                    // Rebuild: walk back through the states, collecting 'current' nodes, then add 'from'.
                    Deque<Node> path = new ArrayDeque<>();
                    for (List<Node> st = next; st != null; st = parent.get(st)) path.addFirst(st.get(1));
                    path.addFirst(from);
                    return new ArrayList<>(path);
                }

                queue.add(next);
            }
        }

        return null;
    }

    /**
     * True if the edge between x and y is x -&gt; y or x - y.
     */
    private static boolean leadsForward(Graph g, Node x, Node y) {
        Edge edge = g.getEdge(x, y);
        if (edge == null) return false;
        if (Edges.isUndirectedEdge(edge)) return true;
        return Edges.isDirectedEdge(edge) && Edges.getDirectedEdgeHead(edge) == y;
    }

    // -------------------------------------------------------------------------------------------------------------
    // Estimation.
    // -------------------------------------------------------------------------------------------------------------

    /**
     * Computes Lambda by regressing each bucket on its external parents (Eq. 18).
     */
    private Matrix computeLambda() {
        int p = nodes.size();
        Matrix lambda = new Matrix(p, p);

        for (Set<Node> bucket : buckets) {
            if (!hasRestrictiveProperty(graph, bucket)) {
                // Cannot happen for a Meek-closed graph (Lemma 3 / Corollary 4), but guard anyway.
                throw new IllegalStateException("Bucket " + bucket + " violates the restrictive property; "
                                                + "the graph is not an MPDAG.");
            }

            Set<Node> parents = externalParents(graph, bucket);
            if (parents.isEmpty()) continue;

            int[] pIdx = indices(parents);
            int[] bIdx = indices(bucket);

            Matrix sigmaPP = cov.getSelection(pIdx, pIdx);
            Matrix sigmaPB = cov.getSelection(pIdx, bIdx);
            Matrix block = sigmaPP.solve(sigmaPB);   // |Pa(B)| x |B|

            for (int r = 0; r < pIdx.length; r++) {
                for (int c = 0; c < bIdx.length; c++) {
                    lambda.set(pIdx[r], bIdx[c], block.get(r, c));
                }
            }
        }

        return lambda;
    }

    /**
     * Returns the estimated total effect of the treatments on the outcome (Eq. 19), as an array aligned with the
     * treatment list. Throws if the effect is not identified.
     *
     * @param treatments The treatment set A (as a list, to fix the order of the returned coefficients).
     * @param outcome    The outcome Y.
     * @return tau_AY, the vector of partial derivatives of E[Y | do(X_A = x_A)] with respect to each x_a.
     * @throws IllegalArgumentException if the effect is not identified, or the nodes are not in the graph.
     */
    public double[] totalEffect(List<Node> treatments, Node outcome) {
        List<Node> a = resolve(treatments);
        Node y = resolve(outcome);
        Set<Node> aSet = new LinkedHashSet<>(a);

        if (aSet.size() != a.size()) throw new IllegalArgumentException("Duplicate treatment.");
        if (aSet.contains(y)) throw new IllegalArgumentException("Outcome must not be a treatment.");

        if (!isIdentified(graph, aSet, y)) {
            throw new IllegalArgumentException("The total effect of " + a + " on " + y
                                               + " is not identified from the MPDAG.");
        }

        // D = An(Y, G_{V \ A}), as a list so we can index into it.
        List<Node> d = new ArrayList<>(ancestorsAvoiding(graph, y, aSet));
        int m = d.size();
        int yPos = d.indexOf(y);

        // (I - Lambda_{D,D})^{-1}, column for Y.
        Matrix iMinusLdd = Matrix.identity(m);
        for (int r = 0; r < m; r++) {
            for (int c = 0; c < m; c++) {
                iMinusLdd.set(r, c, iMinusLdd.get(r, c) - lambda.get(index.get(d.get(r)), index.get(d.get(c))));
            }
        }

        Matrix e = new Matrix(m, 1);
        e.set(yPos, 0, 1.0);
        Matrix col = iMinusLdd.solve(e);   // column Y of (I - Lambda_DD)^{-1}

        double[] tau = new double[a.size()];
        for (int i = 0; i < a.size(); i++) {
            int ai = index.get(a.get(i));
            double s = 0.0;
            for (int j = 0; j < m; j++) {
                s += lambda.get(ai, index.get(d.get(j))) * col.get(j, 0);
            }
            tau[i] = s;
        }

        return tau;
    }

    /**
     * Convenience method for a point intervention.
     *
     * @param treatment The treatment.
     * @param outcome   The outcome.
     * @return The estimated total effect of the treatment on the outcome.
     * @throws IllegalArgumentException if the effect is not identified.
     */
    public double totalEffect(Node treatment, Node outcome) {
        return totalEffect(Collections.singletonList(treatment), outcome)[0];
    }

    /**
     * Returns true if the total effect of the treatments on the outcome is identified from the MPDAG.
     *
     * @param treatments The treatment set.
     * @param outcome    The outcome.
     * @return True if identified.
     */
    public boolean isIdentified(Collection<Node> treatments, Node outcome) {
        return isIdentified(graph, new LinkedHashSet<>(resolve(new ArrayList<>(treatments))), resolve(outcome));
    }

    /**
     * Instance form of {@link #nonIdentificationWitness(Graph, Set, Node)}, resolving nodes by name.
     *
     * @param treatments The treatment set.
     * @param outcome    The outcome.
     * @return A witness path, or null if the effect is identified.
     */
    public List<Node> nonIdentificationWitness(Collection<Node> treatments, Node outcome) {
        List<Node> a = resolve(new ArrayList<>(treatments));
        return nonIdentificationWitness(graph, new LinkedHashSet<>(a), resolve(outcome));
    }

    /**
     * Returns a copy of the block-recursive coefficient matrix Lambda, indexed like the covariance matrix:
     * lambda[i][j] is the coefficient of X_i in the least-squares regression of X_j on the external parents of
     * j's bucket, and zero if i is not such a parent.
     *
     * @return A copy of Lambda.
     */
    public Matrix getLambda() {
        return new Matrix(lambda);
    }

    /**
     * The variable order that indexes the rows and columns of {@link #getLambda()}: the covariance matrix's
     * variable order, mapped to graph nodes. This is generally NOT the same as {@code getGraph().getNodes()},
     * so use this list, not the graph's node order, to read entries of Lambda.
     *
     * @return an unmodifiable list of the graph's nodes in Lambda's index order.
     */
    public List<Node> getVariableOrder() {
        return Collections.unmodifiableList(nodes);
    }

    /**
     * Returns the bucket decomposition used by this estimator.
     *
     * @return The buckets.
     */
    public List<Set<Node>> getBuckets() {
        List<Set<Node>> copy = new ArrayList<>();
        for (Set<Node> b : buckets) copy.add(new LinkedHashSet<>(b));
        return copy;
    }

    /**
     * Returns the MPDAG.
     *
     * @return The graph.
     */
    public Graph getGraph() {
        return graph;
    }

    // -------------------------------------------------------------------------------------------------------------
    // Bootstrap.
    // -------------------------------------------------------------------------------------------------------------

    /**
     * The result of a bootstrapped G-regression estimate.
     *
     * @param treatments The treatment list, fixing the order of the effect vector.
     * @param outcome    The outcome.
     * @param effect     The G-regression estimate on the full sample.
     * @param covariance The bootstrap estimate of the sampling covariance of the effect vector.
     */
    public record BootstrapResult(List<Node> treatments, Node outcome, double[] effect, Matrix covariance) {

        /**
         * Returns the bootstrap standard errors, one per treatment.
         *
         * @return The standard errors.
         */
        public double[] standardErrors() {
            double[] se = new double[effect.length];
            for (int i = 0; i < se.length; i++) se[i] = Math.sqrt(covariance.get(i, i));
            return se;
        }
    }

    /**
     * Estimates a total effect by G-regression on the full data set and estimates its sampling covariance by the
     * nonparametric bootstrap (resampling rows with replacement), as in the eff2 R package. Uses Tetrad's
     * {@link RandomUtil} for the resampling, so it is reproducible by seeding that.
     *
     * @param mpdag         The MPDAG.
     * @param data          A continuous data set over the graph's variables.
     * @param treatments    The treatment list.
     * @param outcome       The outcome.
     * @param numBootstraps The number of bootstrap replications (e.g., 100).
     * @return The estimate and its bootstrap covariance.
     */
    public static BootstrapResult bootstrap(Graph mpdag, DataSet data, List<Node> treatments, Node outcome,
                                            int numBootstraps) {
        if (numBootstraps < 2) throw new IllegalArgumentException("Need at least 2 bootstrap replications.");

        GRegression full = new GRegression(mpdag, new CovarianceMatrix(data));
        double[] effect = full.totalEffect(treatments, outcome);
        int k = effect.length;
        int n = data.getNumRows();

        double[][] draws = new double[numBootstraps][];
        RandomUtil random = RandomUtil.getInstance();

        for (int b = 0; b < numBootstraps; b++) {
            int[] rows = new int[n];
            for (int i = 0; i < n; i++) rows[i] = random.nextInt(n);
            DataSet resampled = data.subsetRows(rows);
            GRegression g = new GRegression(mpdag, new CovarianceMatrix(resampled));
            draws[b] = g.totalEffect(treatments, outcome);
        }

        double[] mean = new double[k];
        for (double[] draw : draws) for (int i = 0; i < k; i++) mean[i] += draw[i] / numBootstraps;

        Matrix covariance = new Matrix(k, k);
        for (double[] draw : draws) {
            for (int i = 0; i < k; i++) {
                for (int j = 0; j < k; j++) {
                    covariance.set(i, j, covariance.get(i, j)
                                         + (draw[i] - mean[i]) * (draw[j] - mean[j]) / (numBootstraps - 1));
                }
            }
        }

        return new BootstrapResult(new ArrayList<>(treatments), outcome, effect, covariance);
    }

    // -------------------------------------------------------------------------------------------------------------
    // Helpers.
    // -------------------------------------------------------------------------------------------------------------

    private int[] indices(Collection<Node> set) {
        int[] idx = new int[set.size()];
        int i = 0;
        for (Node x : set) idx[i++] = index.get(x);
        return idx;
    }

    /**
     * Maps a node (possibly a data variable with the same name) to the corresponding graph node.
     */
    private Node resolve(Node node) {
        if (node == null) throw new IllegalArgumentException("Node is null.");
        if (index.containsKey(node)) return node;
        Node byName = graph.getNode(node.getName());
        if (byName == null || !index.containsKey(byName)) {
            throw new IllegalArgumentException("Node " + node.getName() + " is not a variable of this estimator.");
        }
        return byName;
    }

    private List<Node> resolve(List<Node> list) {
        if (list == null || list.isEmpty()) throw new IllegalArgumentException("Treatment list is empty.");
        List<Node> out = new ArrayList<>(list.size());
        for (Node x : list) out.add(resolve(x));
        return out;
    }
}
